spring:
  ai:
    openai:
      base-url: http://localhost:3000
      api-key: sk-TrQO3wE84wuJEB0z09955aF3A1804964B572C17d4848F397
      chat:
        options:
          model: deepseek-chat

    chat:
      client:
        # true：启用 ChatClient 自动装配，默认启用
        # false：禁用 ChatClient 自动装配
        enabled: true

logging:
  level:
    org.example: debug
    org.springframework.ai.chat.client.advisor: debug

