langchain4j:
  open-ai:
    chat-model:
      api-key: demo
      model-name: gpt-4o-mini

    streaming-chat-model:
      api-key: demo
      model-name: gpt-4o-mini
      base-url: http://langchain4j.dev/demo/openai/v1